### ISSUE TITLE
Issue with Elf-X

### ISSUE THREAD

**Issue by shashankiit** [sindreslungaard/duel-masters#379]
Elf-X card reduces the mana cost for summoning creatures.
In a game after I summoned Elf-X (Effect: Creatures take one mana less to summon)

<img width="279" height="404" alt="Image" src="https://github.com/user-attachments/assets/1199b3f7-a24b-4cc4-aea9-cbb498b0a5f8" />

I had one mana card untapped.
In the current situation I should be able to summon a creature that should normally cost 2 mana.
But I couldn't. The effect came from the next turn.
I checked out the same behaviour in the nintendo version of the game. It allowed me to summon creatures with less mana cost in the same turn.
Can you check this issue?

**Comment by Shahrukh95** [comment]
@shashankiit This behavior has already been fixed in PR #372 (Essence Elf, Elf-X and Cocco Lupia refactor).

The mana reduction effect was implemented as a persistent effect. Therefore, creatures can be summoned with the reduced cost in the same turn Elf-X is played, matching the Nintendo version behavior.

**Comment by QuasarBlazar1995** [comment]
It has not been fixed entirely. I still have issues with it if I summon Elf X first, then in the same turn, after him, Sometimes the effect is not in place, although I have enough mana
